apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: default-psp
  labels:
    rbac.authorization.k8s.io/aggregate-to-poweruser: "true"
rules:
- apiGroups:
  - extensions
  resources:
  - podsecuritypolicies
  resourceNames:
  - default
  verbs:
  - use
